config/routes.rb
GreenThumb::Application.routes.draw do
  resources :categories

  root to: "products#index"

  devise_for :users, :controllers => {:registrations => 'registrations'} do
    get 'logout' => 'devise/sessions#destroy'
  end

  resources :products

  resources :users do
    post "save_profile", :on => :collection
  end
  get "/user/profile" => "users#profile"

  resources :authentications, only: [:index, :create, :destroy]
  match '/auth/:provider/callback' => 'authentications#create', via: [:post, :get]

  namespace :api do
    resources :products do
      post 'vote_by'
    end
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
	has_many :product_categories, :dependent => :destroy
    has_many :products, :through => :product_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :validate_admin_user
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: {class: 'form-inline'}) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', required: true, autofocus: true, placeholder: "Name" %>
    <%= f.submit "Save", class: 'btn btn-primary' %>
    <%= link_to 'Back', categories_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
	<h1>Editing category</h1>

	<%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="bs-example bs-example-bg-classes">
    <p class="bg-success">Categories</p>
    <%= link_to 'New Category', new_category_path, class: 'btn btn-default' %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name rescue '' %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %> | <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
	<h1>New category</h1>

	<%= render 'form' %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>